name: E2E Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  vitest-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all ViTest tests
      - name: ViTest setup
        run: npm install
      - name: ViTest run
        run: npm run test:unit
